In [1]:
print("Hello")

Hello


In [2]:
print("Hello")

Hello


In [3]:
import pandas as pd
df=pd.read_csv("Datasets/movies.csv")

In [4]:
df

star_rating                                            title  \
0            9.3                         The Shawshank Redemption   
1            9.2                                    The Godfather   
2            9.1                           The Godfather: Part II   
3            9.0                                  The Dark Knight   
4            8.9                                     Pulp Fiction   
..           ...                                              ...   
974          7.4                                          Tootsie   
975          7.4                      Back to the Future Part III   
976          7.4  Master and Commander: The Far Side of the World   
977          7.4                                      Poltergeist   
978          7.4                                      Wall Street   

    content_rating      genre  duration  \
0                R      Crime       142   
1                R      Crime       175   
2                R      Crime       200   
3            PG-13     Action       152   
4                R      Crime       154   
..             ...        ...       ...   
974             PG     Comedy       116   
975             PG  Adventure       118   
976          PG-13     Action       138   
977             PG     Horror       114   
978              R      Crime       126   

                                           actors_list  
0    [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1      [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2    [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3    [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4    [u'John Travolta', u'Uma Thurman', u'Samuel L....  
..                                                 ...  
974  [u'Dustin Hoffman', u'Jessica Lange', u'Teri G...  
975  [u'Michael J. Fox', u'Christopher Lloyd', u'Ma...  
976  [u'Russell Crowe', u'Paul Bettany', u'Billy Bo...  
977  [u'JoBeth Williams', u"Heather O'Rourke", u'Cr...  
978  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...  

[979 rows x 6 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 979 entries, 0 to 978
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   star_rating     979 non-null    float64
 1   title           979 non-null    object 
 2   content_rating  976 non-null    object 
 3   genre           979 non-null    object 
 4   duration        979 non-null    int64  
 5   actors_list     979 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 46.0+ KB


df.info()


In [6]:
df.genre.unique().shape

(16,)

In [7]:
df

star_rating                                            title  \
0            9.3                         The Shawshank Redemption   
1            9.2                                    The Godfather   
2            9.1                           The Godfather: Part II   
3            9.0                                  The Dark Knight   
4            8.9                                     Pulp Fiction   
..           ...                                              ...   
974          7.4                                          Tootsie   
975          7.4                      Back to the Future Part III   
976          7.4  Master and Commander: The Far Side of the World   
977          7.4                                      Poltergeist   
978          7.4                                      Wall Street   

    content_rating      genre  duration  \
0                R      Crime       142   
1                R      Crime       175   
2                R      Crime       200   
3            PG-13     Action       152   
4                R      Crime       154   
..             ...        ...       ...   
974             PG     Comedy       116   
975             PG  Adventure       118   
976          PG-13     Action       138   
977             PG     Horror       114   
978              R      Crime       126   

                                           actors_list  
0    [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1      [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2    [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3    [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4    [u'John Travolta', u'Uma Thurman', u'Samuel L....  
..                                                 ...  
974  [u'Dustin Hoffman', u'Jessica Lange', u'Teri G...  
975  [u'Michael J. Fox', u'Christopher Lloyd', u'Ma...  
976  [u'Russell Crowe', u'Paul Bettany', u'Billy Bo...  
977  [u'JoBeth Williams', u"Heather O'Rourke", u'Cr...  
978  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...  

[979 rows x 6 columns]

In [8]:
import numpy as np

In [9]:
np.__version__

'1.18.1'

In [10]:
np.byte_bounds?

Signature: np.byte_bounds(a)
Docstring:
Returns pointers to the end-points of an array.

Parameters
----------
a : ndarray
    Input array. It must conform to the Python-side of the array
    interface.

Returns
-------
(low, high) : tuple of 2 integers
    The first integer is the first byte of the array, the second
    integer is just past the last byte of the array.  If `a` is not
    contiguous it will not use every byte between the (`low`, `high`)
    values.

Examples
--------
>>> I = np.eye(2, dtype='f'); I.dtype
dtype('float32')
>>> low, high = np.byte_bounds(I)
>>> high - low == I.size*I.itemsize
True
>>> I = np.eye(2); I.dtype
dtype('float64')
>>> low, high = np.byte_bounds(I)
>>> high - low == I.size*I.itemsize
True
File:      c:\users\kishan verma\anaconda3\lib\site-packages\numpy\lib\utils.py
Type:      function


In [11]:
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Kishan Verma\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\kishan verma\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  

In [12]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : 

np.random.randint?

In [13]:
x=np.random.randint(100, size=(100, 100))
x.nbytes

40000

In [14]:
x[0, 0]=10.2

In [15]:
x[0,0]

10

In [16]:
x=np.random.randint(20, size=(10,10))
x

array([[16,  8, 18,  2, 10, 14,  6,  4, 12, 18],
       [ 1, 13, 19,  5, 14,  7, 15,  8,  6,  7],
       [ 4,  0,  2, 18,  3, 13,  0,  7, 10, 11],
       [17,  9, 14,  9, 17,  0,  3,  4,  2,  2],
       [10, 11,  9, 10,  3,  1,  5,  4, 14, 11],
       [11,  0, 10, 17, 16,  4, 15, 11,  3, 15],
       [13, 12, 10,  9,  4, 16,  8,  0,  2,  5],
       [13, 15,  2, 10,  9,  5,  5, 11,  0,  1],
       [ 3,  4,  7,  3,  9, 17,  6,  2,  4,  1],
       [19,  0,  2, 17,  4, 11, 13,  2,  6,  9]])

In [17]:
x[2:,2:]

array([[ 2, 18,  3, 13,  0,  7, 10, 11],
       [14,  9, 17,  0,  3,  4,  2,  2],
       [ 9, 10,  3,  1,  5,  4, 14, 11],
       [10, 17, 16,  4, 15, 11,  3, 15],
       [10,  9,  4, 16,  8,  0,  2,  5],
       [ 2, 10,  9,  5,  5, 11,  0,  1],
       [ 7,  3,  9, 17,  6,  2,  4,  1],
       [ 2, 17,  4, 11, 13,  2,  6,  9]])

In [18]:
x[:2, :2]

array([[16,  8],
       [ 1, 13]])

In [19]:
x[::-1, ::-1]

array([[ 9,  6,  2, 13, 11,  4, 17,  2,  0, 19],
       [ 1,  4,  2,  6, 17,  9,  3,  7,  4,  3],
       [ 1,  0, 11,  5,  5,  9, 10,  2, 15, 13],
       [ 5,  2,  0,  8, 16,  4,  9, 10, 12, 13],
       [15,  3, 11, 15,  4, 16, 17, 10,  0, 11],
       [11, 14,  4,  5,  1,  3, 10,  9, 11, 10],
       [ 2,  2,  4,  3,  0, 17,  9, 14,  9, 17],
       [11, 10,  7,  0, 13,  3, 18,  2,  0,  4],
       [ 7,  6,  8, 15,  7, 14,  5, 19, 13,  1],
       [18, 12,  4,  6, 14, 10,  2, 18,  8, 16]])

In [20]:
x

array([[16,  8, 18,  2, 10, 14,  6,  4, 12, 18],
       [ 1, 13, 19,  5, 14,  7, 15,  8,  6,  7],
       [ 4,  0,  2, 18,  3, 13,  0,  7, 10, 11],
       [17,  9, 14,  9, 17,  0,  3,  4,  2,  2],
       [10, 11,  9, 10,  3,  1,  5,  4, 14, 11],
       [11,  0, 10, 17, 16,  4, 15, 11,  3, 15],
       [13, 12, 10,  9,  4, 16,  8,  0,  2,  5],
       [13, 15,  2, 10,  9,  5,  5, 11,  0,  1],
       [ 3,  4,  7,  3,  9, 17,  6,  2,  4,  1],
       [19,  0,  2, 17,  4, 11, 13,  2,  6,  9]])

In [21]:
x[::2, ::2]

array([[16, 18, 10,  6, 12],
       [ 4,  2,  3,  0, 10],
       [10,  9,  3,  5, 14],
       [13, 10,  4,  8,  2],
       [ 3,  7,  9,  6,  4]])

In [22]:
x[0, ::-1]

array([18, 12,  4,  6, 14, 10,  2, 18,  8, 16])

In [23]:
y=x[:, :2]
y
y[0,0]=0
x

array([[ 0,  8, 18,  2, 10, 14,  6,  4, 12, 18],
       [ 1, 13, 19,  5, 14,  7, 15,  8,  6,  7],
       [ 4,  0,  2, 18,  3, 13,  0,  7, 10, 11],
       [17,  9, 14,  9, 17,  0,  3,  4,  2,  2],
       [10, 11,  9, 10,  3,  1,  5,  4, 14, 11],
       [11,  0, 10, 17, 16,  4, 15, 11,  3, 15],
       [13, 12, 10,  9,  4, 16,  8,  0,  2,  5],
       [13, 15,  2, 10,  9,  5,  5, 11,  0,  1],
       [ 3,  4,  7,  3,  9, 17,  6,  2,  4,  1],
       [19,  0,  2, 17,  4, 11, 13,  2,  6,  9]])

In [24]:
y.reshape(5,4)

array([[ 0,  8,  1, 13],
       [ 4,  0, 17,  9],
       [10, 11, 11,  0],
       [13, 12, 13, 15],
       [ 3,  4, 19,  0]])

In [25]:
x

array([[ 0,  8, 18,  2, 10, 14,  6,  4, 12, 18],
       [ 1, 13, 19,  5, 14,  7, 15,  8,  6,  7],
       [ 4,  0,  2, 18,  3, 13,  0,  7, 10, 11],
       [17,  9, 14,  9, 17,  0,  3,  4,  2,  2],
       [10, 11,  9, 10,  3,  1,  5,  4, 14, 11],
       [11,  0, 10, 17, 16,  4, 15, 11,  3, 15],
       [13, 12, 10,  9,  4, 16,  8,  0,  2,  5],
       [13, 15,  2, 10,  9,  5,  5, 11,  0,  1],
       [ 3,  4,  7,  3,  9, 17,  6,  2,  4,  1],
       [19,  0,  2, 17,  4, 11, 13,  2,  6,  9]])

In [26]:
y

array([[ 0,  8],
       [ 1, 13],
       [ 4,  0],
       [17,  9],
       [10, 11],
       [11,  0],
       [13, 12],
       [13, 15],
       [ 3,  4],
       [19,  0]])

In [27]:
np.hstack([x, y])

array([[ 0,  8, 18,  2, 10, 14,  6,  4, 12, 18,  0,  8],
       [ 1, 13, 19,  5, 14,  7, 15,  8,  6,  7,  1, 13],
       [ 4,  0,  2, 18,  3, 13,  0,  7, 10, 11,  4,  0],
       [17,  9, 14,  9, 17,  0,  3,  4,  2,  2, 17,  9],
       [10, 11,  9, 10,  3,  1,  5,  4, 14, 11, 10, 11],
       [11,  0, 10, 17, 16,  4, 15, 11,  3, 15, 11,  0],
       [13, 12, 10,  9,  4, 16,  8,  0,  2,  5, 13, 12],
       [13, 15,  2, 10,  9,  5,  5, 11,  0,  1, 13, 15],
       [ 3,  4,  7,  3,  9, 17,  6,  2,  4,  1,  3,  4],
       [19,  0,  2, 17,  4, 11, 13,  2,  6,  9, 19,  0]])

In [28]:
print(x, y)

[[ 0  8 18  2 10 14  6  4 12 18]
 [ 1 13 19  5 14  7 15  8  6  7]
 [ 4  0  2 18  3 13  0  7 10 11]
 [17  9 14  9 17  0  3  4  2  2]
 [10 11  9 10  3  1  5  4 14 11]
 [11  0 10 17 16  4 15 11  3 15]
 [13 12 10  9  4 16  8  0  2  5]
 [13 15  2 10  9  5  5 11  0  1]
 [ 3  4  7  3  9 17  6  2  4  1]
 [19  0  2 17  4 11 13  2  6  9]] [[ 0  8]
 [ 1 13]
 [ 4  0]
 [17  9]
 [10 11]
 [11  0]
 [13 12]
 [13 15]
 [ 3  4]
 [19  0]]


In [29]:
x+x

array([[ 0, 16, 36,  4, 20, 28, 12,  8, 24, 36],
       [ 2, 26, 38, 10, 28, 14, 30, 16, 12, 14],
       [ 8,  0,  4, 36,  6, 26,  0, 14, 20, 22],
       [34, 18, 28, 18, 34,  0,  6,  8,  4,  4],
       [20, 22, 18, 20,  6,  2, 10,  8, 28, 22],
       [22,  0, 20, 34, 32,  8, 30, 22,  6, 30],
       [26, 24, 20, 18,  8, 32, 16,  0,  4, 10],
       [26, 30,  4, 20, 18, 10, 10, 22,  0,  2],
       [ 6,  8, 14,  6, 18, 34, 12,  4,  8,  2],
       [38,  0,  4, 34,  8, 22, 26,  4, 12, 18]])

In [30]:
x**2

array([[  0,  64, 324,   4, 100, 196,  36,  16, 144, 324],
       [  1, 169, 361,  25, 196,  49, 225,  64,  36,  49],
       [ 16,   0,   4, 324,   9, 169,   0,  49, 100, 121],
       [289,  81, 196,  81, 289,   0,   9,  16,   4,   4],
       [100, 121,  81, 100,   9,   1,  25,  16, 196, 121],
       [121,   0, 100, 289, 256,  16, 225, 121,   9, 225],
       [169, 144, 100,  81,  16, 256,  64,   0,   4,  25],
       [169, 225,   4, 100,  81,  25,  25, 121,   0,   1],
       [  9,  16,  49,   9,  81, 289,  36,   4,  16,   1],
       [361,   0,   4, 289,  16, 121, 169,   4,  36,  81]], dtype=int32)

In [31]:
x

array([[ 0,  8, 18,  2, 10, 14,  6,  4, 12, 18],
       [ 1, 13, 19,  5, 14,  7, 15,  8,  6,  7],
       [ 4,  0,  2, 18,  3, 13,  0,  7, 10, 11],
       [17,  9, 14,  9, 17,  0,  3,  4,  2,  2],
       [10, 11,  9, 10,  3,  1,  5,  4, 14, 11],
       [11,  0, 10, 17, 16,  4, 15, 11,  3, 15],
       [13, 12, 10,  9,  4, 16,  8,  0,  2,  5],
       [13, 15,  2, 10,  9,  5,  5, 11,  0,  1],
       [ 3,  4,  7,  3,  9, 17,  6,  2,  4,  1],
       [19,  0,  2, 17,  4, 11, 13,  2,  6,  9]])

In [32]:
np.dstack([x, x])

array([[[ 0,  0],
        [ 8,  8],
        [18, 18],
        [ 2,  2],
        [10, 10],
        [14, 14],
        [ 6,  6],
        [ 4,  4],
        [12, 12],
        [18, 18]],

       [[ 1,  1],
        [13, 13],
        [19, 19],
        [ 5,  5],
        [14, 14],
        [ 7,  7],
        [15, 15],
        [ 8,  8],
        [ 6,  6],
        [ 7,  7]],

       [[ 4,  4],
        [ 0,  0],
        [ 2,  2],
        [18, 18],
        [ 3,  3],
        [13, 13],
        [ 0,  0],
        [ 7,  7],
        [10, 10],
        [11, 11]],

       [[17, 17],
        [ 9,  9],
        [14, 14],
        [ 9,  9],
        [17, 17],
        [ 0,  0],
        [ 3,  3],
        [ 4,  4],
        [ 2,  2],
        [ 2,  2]],

       [[10, 10],
        [11, 11],
        [ 9,  9],
        [10, 10],
        [ 3,  3],
        [ 1,  1],
        [ 5,  5],
        [ 4,  4],
        [14, 14],
        [11, 11]],

       [[11, 11],
        [ 0,  0],
        [10, 10],
        [17, 17],
        [16, 16],


In [33]:
z=np.random.randint(10, size=20)
z

array([1, 2, 5, 8, 0, 0, 6, 8, 7, 3, 1, 9, 3, 1, 7, 1, 5, 3, 9, 1])

In [34]:
np.split(z, [3, 1])

[array([1, 2, 5]),
 array([], dtype=int32),
 array([2, 5, 8, 0, 0, 6, 8, 7, 3, 1, 9, 3, 1, 7, 1, 5, 3, 9, 1])]

In [35]:
x

array([[ 0,  8, 18,  2, 10, 14,  6,  4, 12, 18],
       [ 1, 13, 19,  5, 14,  7, 15,  8,  6,  7],
       [ 4,  0,  2, 18,  3, 13,  0,  7, 10, 11],
       [17,  9, 14,  9, 17,  0,  3,  4,  2,  2],
       [10, 11,  9, 10,  3,  1,  5,  4, 14, 11],
       [11,  0, 10, 17, 16,  4, 15, 11,  3, 15],
       [13, 12, 10,  9,  4, 16,  8,  0,  2,  5],
       [13, 15,  2, 10,  9,  5,  5, 11,  0,  1],
       [ 3,  4,  7,  3,  9, 17,  6,  2,  4,  1],
       [19,  0,  2, 17,  4, 11, 13,  2,  6,  9]])

In [36]:
np.split(x, [3, 7])

[array([[ 0,  8, 18,  2, 10, 14,  6,  4, 12, 18],
        [ 1, 13, 19,  5, 14,  7, 15,  8,  6,  7],
        [ 4,  0,  2, 18,  3, 13,  0,  7, 10, 11]]),
 array([[17,  9, 14,  9, 17,  0,  3,  4,  2,  2],
        [10, 11,  9, 10,  3,  1,  5,  4, 14, 11],
        [11,  0, 10, 17, 16,  4, 15, 11,  3, 15],
        [13, 12, 10,  9,  4, 16,  8,  0,  2,  5]]),
 array([[13, 15,  2, 10,  9,  5,  5, 11,  0,  1],
        [ 3,  4,  7,  3,  9, 17,  6,  2,  4,  1],
        [19,  0,  2, 17,  4, 11, 13,  2,  6,  9]])]

In [37]:
np.hsplit(x, [3, 5])

[array([[ 0,  8, 18],
        [ 1, 13, 19],
        [ 4,  0,  2],
        [17,  9, 14],
        [10, 11,  9],
        [11,  0, 10],
        [13, 12, 10],
        [13, 15,  2],
        [ 3,  4,  7],
        [19,  0,  2]]),
 array([[ 2, 10],
        [ 5, 14],
        [18,  3],
        [ 9, 17],
        [10,  3],
        [17, 16],
        [ 9,  4],
        [10,  9],
        [ 3,  9],
        [17,  4]]),
 array([[14,  6,  4, 12, 18],
        [ 7, 15,  8,  6,  7],
        [13,  0,  7, 10, 11],
        [ 0,  3,  4,  2,  2],
        [ 1,  5,  4, 14, 11],
        [ 4, 15, 11,  3, 15],
        [16,  8,  0,  2,  5],
        [ 5,  5, 11,  0,  1],
        [17,  6,  2,  4,  1],
        [11, 13,  2,  6,  9]])]

In [38]:
x

array([[ 0,  8, 18,  2, 10, 14,  6,  4, 12, 18],
       [ 1, 13, 19,  5, 14,  7, 15,  8,  6,  7],
       [ 4,  0,  2, 18,  3, 13,  0,  7, 10, 11],
       [17,  9, 14,  9, 17,  0,  3,  4,  2,  2],
       [10, 11,  9, 10,  3,  1,  5,  4, 14, 11],
       [11,  0, 10, 17, 16,  4, 15, 11,  3, 15],
       [13, 12, 10,  9,  4, 16,  8,  0,  2,  5],
       [13, 15,  2, 10,  9,  5,  5, 11,  0,  1],
       [ 3,  4,  7,  3,  9, 17,  6,  2,  4,  1],
       [19,  0,  2, 17,  4, 11, 13,  2,  6,  9]])

In [39]:
np.vsplit(x, [3, 5])

[array([[ 0,  8, 18,  2, 10, 14,  6,  4, 12, 18],
        [ 1, 13, 19,  5, 14,  7, 15,  8,  6,  7],
        [ 4,  0,  2, 18,  3, 13,  0,  7, 10, 11]]),
 array([[17,  9, 14,  9, 17,  0,  3,  4,  2,  2],
        [10, 11,  9, 10,  3,  1,  5,  4, 14, 11]]),
 array([[11,  0, 10, 17, 16,  4, 15, 11,  3, 15],
        [13, 12, 10,  9,  4, 16,  8,  0,  2,  5],
        [13, 15,  2, 10,  9,  5,  5, 11,  0,  1],
        [ 3,  4,  7,  3,  9, 17,  6,  2,  4,  1],
        [19,  0,  2, 17,  4, 11, 13,  2,  6,  9]])]

In [40]:
np.arange(5
        )

array([0, 1, 2, 3, 4])

In [41]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [42]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [43]:
x=np.arange(10
         )
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.add.reduce(x)

45

In [45]:
np.subtract.reduce(x)

-45

In [46]:
np.multiply.reduce(x)

0

In [47]:
np.add.accumulate(x)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [48]:
np.multiply.accumulate(x)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [49]:
np.arange(2, 21, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [50]:
np.multiply.outer(np.arange(1, 5), np.arange(2, 6))

array([[ 2,  3,  4,  5],
       [ 4,  6,  8, 10],
       [ 6,  9, 12, 15],
       [ 8, 12, 16, 20]])

In [51]:
x=np.arange(1, 5)
x

array([1, 2, 3, 4])

In [52]:
y=np.arange(2, 6)
y

array([2, 3, 4, 5])

In [53]:
x=np.random.random(1000
                )
x

array([1.90735751e-02, 4.18909372e-01, 2.81781918e-01, 2.54192942e-01,
       8.98127150e-01, 3.33085986e-01, 6.45970409e-02, 1.82002476e-01,
       2.25553268e-01, 7.46737056e-01, 5.57331935e-01, 2.35723471e-02,
       2.54091277e-01, 8.95432023e-02, 2.23028594e-01, 7.22392167e-01,
       5.91296632e-01, 9.49872267e-01, 5.90842566e-01, 1.52834475e-01,
       6.12898746e-01, 1.71801015e-01, 2.35114098e-02, 7.59442780e-01,
       7.05928256e-01, 3.75881878e-01, 6.06169393e-02, 9.90100802e-01,
       3.71573472e-01, 3.26071300e-01, 6.04218978e-01, 8.36479441e-01,
       1.24575148e-01, 6.17353798e-01, 6.21577318e-01, 2.86769035e-01,
       5.64199993e-01, 9.60695534e-01, 3.55900158e-01, 9.84500447e-02,
       1.48714097e-01, 3.62318570e-02, 1.83942423e-01, 4.84511972e-01,
       3.76095550e-01, 1.72979948e-02, 3.66875343e-01, 2.70299990e-01,
       1.27604478e-01, 5.15451638e-01, 7.14293162e-01, 1.24366213e-01,
       5.86339415e-01, 3.94555940e-01, 6.85672982e-02, 1.73768185e-01,
      

In [54]:
np.sum(x)

497.1867184789743

In [55]:
sum(x)

497.1867184789747

In [56]:
%timeit sum(x)

678 µs ± 81.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [57]:
%timeit np.sum(x)

24.9 µs ± 3.63 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [58]:
np.random.rand(1000)

array([6.05032186e-01, 9.13530266e-03, 5.47647439e-01, 9.76329026e-01,
       1.47630715e-01, 1.31612025e-01, 2.85349322e-01, 8.53232461e-01,
       8.71606372e-01, 2.65904383e-01, 9.85869563e-01, 8.76465258e-01,
       7.76220764e-02, 4.38108025e-01, 2.55328372e-01, 1.57702990e-01,
       5.89468789e-01, 5.07596925e-01, 5.38974400e-01, 5.55129055e-01,
       1.95291380e-01, 2.72738888e-01, 5.67185106e-01, 9.68806043e-01,
       9.46607096e-01, 1.13701082e-01, 7.55355024e-02, 6.07031092e-02,
       8.85804984e-01, 7.76743387e-01, 5.73772742e-01, 5.73148938e-01,
       4.22643183e-01, 1.59919867e-01, 4.67899307e-01, 4.81196159e-01,
       7.66035558e-01, 6.98225468e-01, 9.84542853e-01, 2.16968253e-01,
       5.83994639e-01, 6.31640991e-01, 2.10349791e-01, 4.24718793e-01,
       7.75689023e-01, 2.87922382e-01, 1.88685892e-01, 9.08658608e-01,
       6.22057598e-01, 9.96836808e-01, 5.19732549e-01, 2.40348396e-01,
       1.08169953e-02, 1.34650557e-01, 5.28179869e-01, 8.58603632e-01,
      

In [59]:
np.random.random?

Docstring:
random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.
Type:      builtin_function_or_method


In [60]:
x=np.random.rand(100000)
x

array([0.05691233, 0.11665335, 0.57675391, ..., 0.45788456, 0.02358045,
       0.45658142])

In [61]:
min(x), max(x)

(7.386398159781038e-10, 0.9999814208731143)

In [62]:
%timeit np.min(x), np.max(x)

232 µs ± 54.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [63]:
%timeit min(x), max(x)

82.1 ms ± 3.86 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [64]:
np.random.randint(3, 10, size=5)

array([9, 8, 8, 6, 3])

In [65]:
np.random.rand?

Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random
Type:      builtin_function_or_method


In [66]:
np.sum(x)

49875.69985295342

In [67]:
x=np.random.random([500, 400])
x

array([[0.56966475, 0.18324964, 0.60412836, ..., 0.86702297, 0.71372754,
        0.68977793],
       [0.13486415, 0.90177398, 0.04880236, ..., 0.67128203, 0.96385786,
        0.08242146],
       [0.37665015, 0.54418831, 0.29093553, ..., 0.90448203, 0.11478305,
        0.13199156],
       ...,
       [0.73743397, 0.42982778, 0.62932083, ..., 0.14722904, 0.37746539,
        0.68306422],
       [0.71593507, 0.83094569, 0.54699399, ..., 0.49680768, 0.73379793,
        0.04060434],
       [0.81214817, 0.0174234 , 0.57741829, ..., 0.50122317, 0.54459944,
        0.78007883]])

In [68]:
a=np.sum(x, axis=1)
a

array([203.23844121, 191.68574119, 192.7610835 , 194.08863979,
       192.8866302 , 195.94292031, 198.88636586, 193.44954821,
       213.58784291, 206.26779769, 202.16810158, 202.11683152,
       200.1546641 , 199.64591009, 208.32378422, 209.65473387,
       207.00378468, 194.52917645, 190.23216723, 200.63127743,
       197.00018528, 192.55279877, 197.18992277, 199.3359503 ,
       207.51679554, 197.10432399, 197.9892627 , 193.05263119,
       196.38697459, 195.01633362, 206.13336049, 199.51052734,
       204.62170266, 201.07646091, 205.33617415, 203.5445181 ,
       205.00396093, 204.49326141, 202.90621233, 194.96348819,
       199.46013754, 204.61007401, 204.02085922, 205.63206404,
       200.73980233, 198.17860108, 196.15023996, 200.78143014,
       188.99238403, 195.32401217, 200.40638182, 193.48811016,
       194.64031098, 207.03181575, 196.18729596, 192.24443172,
       208.94696015, 191.68944023, 199.95284465, 201.22714521,
       203.27718926, 191.4326836 , 198.55711577, 187.69

In [69]:
b=np.sum(x, axis=0)
b

array([254.44931108, 242.89829417, 248.61751443, 248.57750856,
       247.2231315 , 256.51743073, 257.68193329, 239.72677046,
       244.60202653, 261.1541573 , 248.46045593, 248.98073204,
       253.50697628, 255.13830486, 252.35980684, 254.34719801,
       245.27150913, 251.47260064, 235.81277892, 241.93102911,
       250.64316944, 257.83812756, 238.72643531, 237.5693201 ,
       249.31417268, 256.51845278, 235.55741893, 252.20832717,
       249.92955457, 246.04551775, 249.86162441, 254.81696147,
       232.97673322, 240.61082625, 249.87212882, 244.70845404,
       241.82983836, 248.96018434, 247.18574586, 258.24593455,
       252.16539253, 258.60962968, 248.80107226, 244.32066837,
       253.46131129, 249.95424155, 250.22073698, 249.53340791,
       255.90895566, 248.34491524, 246.02676387, 257.47664801,
       248.00997286, 254.45298582, 244.92946125, 241.48379928,
       251.60170371, 246.42249438, 260.2714431 , 247.55338976,
       254.43887457, 257.13348164, 254.84751598, 248.51

In [70]:
np.median(a)

199.8393685041423

In [71]:
np.median(b)

249.60480862539555

In [72]:
np.percentile?

Signature:
np.percentile(
    a,
    q,
    axis=None,
    out=None,
    overwrite_input=False,
    interpolation='linear',
    keepdims=False,
)
Docstring:
Compute the q-th percentile of the data along the specified axis.

Returns the q-th percentile(s) of the array elements.

Parameters
----------
a : array_like
    Input array or object that can be converted to an array.
q : array_like of float
    Percentile or sequence of percentiles to compute, which must be between
    0 and 100 inclusive.
axis : {int, tuple of int, None}, optional
    Axis or axes along which the percentiles are computed. The
    default is to compute the percentile(s) along a flattened
    version of the array.

    .. versionchanged:: 1.9.0
        A tuple of axes is supported
out : ndarray, optional
    Alternative output array in which to place the result. It must
    have the same shape and buffer length as the expected output,
    but the type (of the output) will be cast if necessary.
overwrite_input : b

In [73]:
import pandas as pd
train  = pd.read_csv("Datasets/train.csv")
test = pd.read_csv("Datasets/test.csv")


In [74]:
train.workclass.value_counts(sort=True)
train.workclass.fillna('Private',inplace=True)
train.occupation.value_counts(sort=True)
train.occupation.fillna('Prof-specialty',inplace=True)
train['native.country'].value_counts(sort=True)
train['native.country'].fillna('United-States',inplace=True)

In [75]:
train.head()

age          workclass  fnlwgt   education  education.num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital.status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital.gain  capital.loss  hours.per.week  native.country  target  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [76]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

y = train['target']
del train['target']

X = train
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1,stratify=y)

#train the RF classifier
clf = RandomForestClassifier(n_estimators = 500, max_depth = 6)
clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini', max_depth=6, max_features='auto', max_leaf_nodes=None, min_impurity_split=1e-07, min_samples_leaf=1, min_samples_split=2, min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=1, oob_score=False, random_state=None, verbose=0, warm_start=False)

clf.predict(X_test)

ValueError: could not convert string to float: ' Federal-gov'

In [77]:
import numpy as np
prediction = clf.predict(X_test)
acc =  accuracy_score(np.array(y_test),prediction)
print ('The accuracy of Random Forest is {}'.format(acc))

NotFittedError: This RandomForestClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.